### ISSUE TITLE
Make ExamTasks "finishable"

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#10]
@needToRoll proposed that we add a flag on `ExamTask` (Lernziel) that allows users to mark it as finished. What are your opinions?

@outcobra/developers

**Comment by needToRoll** [comment]
I woud like to say that:

1. For now it is a minor change... 
2. For big tests it might be useful to have the option to do that
3. @bweben said "if this feature does not exitst the ExamTask seems useless"

**Comment by jmesserli** [comment]
I personally don't think it's necessary but it's one attribute to change and if it provides value to some people, we might as well add it.

**Comment by needToRoll** [comment]
According to a discussion we ( @outcobra/developers ) have decided to make the change.
