### ISSUE TITLE
Define Spring Profiles

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#103]
We should define all the spring profiles we will need so that we can implement them in #47 in preferrably the next sprint.

**Comment by needToRoll** [comment]
whats the status on this?

**Comment by jmesserli** [comment]
I'll do it tomorrow, should be a quick one.

**Comment by M4R1KU** [comment]
@jmesserli what's your progress on this issue?

**Comment by jmesserli** [comment]
I had a shit of a headache and went to sleep instead of doing anything else
yesterday. So no progress.

Mario Kunz <notifications@github.com> schrieb am Do., 26. Jan. 2017, 16:34:

**Comment by jmesserli** [comment]
So far I think those are the ones that will be useful to us:
* Use H2, Postgres, MySQL
 * When H2 is enabled, H2 console
* Load testdata
* Security mock (basic auth)

Can't really think of any others. Maybe you guys have some more obvious ones @M4R1KU @needToRoll ?

**Comment by M4R1KU** [comment]
@jmesserli sounds good atm

***future***
will flyway probably also have an impact to new profiles?
and if we are going to implement mail notifications we probably also have to add mail profiles like they are in MIKOS.

**Comment by jmesserli** [comment]
@M4R1KU yeah flyway will probably be handled by the accompanying db profile probably. 
Mail profiles I thought about but then I remembered that you guys seemed to hate mails anyway and I left them out because of that :joy:

**Comment by M4R1KU** [comment]
I am sure we are going to have mails sometime in the future but not im the open beta i think. => 2018
I just wrote as reminder for the future bc nobody will never ever read through this issue after it's closed.😂

**Comment by jmesserli** [comment]
Ah disable auth filter might be a good one too, depending on if we get it fixed.
