### ISSUE TITLE
Just write more tests

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#106]
Areas where we should write Unit-Tests.

- [x] Services with validation (SchoolYear, Semester)
- [ ] Task
- [ ] If we are bored we can make UI-Tests with Jasmine

... please add more

**Comment by jmesserli** [comment]
Any updates, @needToRoll I think you were working on something here? Not that we do the same things.

**Comment by needToRoll** [comment]
Yes I am... the service and validator tests.

**Comment by needToRoll** [comment]
status:
- SchoolYearValidator integration (service level) tests are done and pushed
- Overlap unittests are in progress (local)
- SemesterValidationTest are still open, todo -> planed for tomorrow
