### ISSUE TITLE
Clean up branches on github

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#108]
We should delete all branches that are no longer needed on github. It looks quite messy right now.

**Comment by needToRoll** [comment]
create-task can be deleted
I am not able to... (I do not have the permission)

**Comment by needToRoll** [comment]
what else is to do there?

**Comment by jmesserli** [comment]
![image](https://cloud.githubusercontent.com/assets/613138/22281854/705494fc-e2d9-11e6-8ee4-b4f0577fa729.png)
 I marked all the branches that can be potentially removed. `feature/task-ui` is marked because we should create a new branch for the updating and stuff. The branch is too large imo.

**Comment by jmesserli** [comment]
Deleted four branches, the other ones I can't delete yet. Keeping this open to track progress.

**Comment by M4R1KU** [comment]
I think this is mostly finished. We could delete `amend/34-timepicker` because it's just too old and it seems like there is change to keep on this branch.
