### ISSUE TITLE
Create plan for next features

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#110]
We should plan which features or epics we want to implement next. I think it would also be good to maybe start a wiki where we can document our roadmap a bit. This will help planning issues that have no milestone like mentioned in #34.

**Comment by needToRoll** [comment]
I agree, in my opinion the next steps should be:

1. impl update
2. impl Exams
3. impl Marks
4. impl Reportings
5. impl Teacher
6. impl TT

**Comment by jmesserli** [comment]
TBH, timetable is kind of the most used feature by me so I'd love for it to not be the last thing we do. On the other hand, it's something I can do well with MyStudyLife for the time being.

I'd take marks before exams because it is more important to me than exams and adds more value for us all. What do you think @M4R1KU, @needToRoll?

**Comment by needToRoll** [comment]
It seems pointless to implement marks without exams doesn't it?

**Comment by jmesserli** [comment]
Not at all, does Gradebook seem pointless to you? That doesn't have exams either.

**Comment by needToRoll** [comment]
ok no, but its more fancy with the exams...

How about

1. impl editing (update)
2. impl Marks
3.  impl Exams
4. impl TT
5. impl Reportings
6. impl Teacher

**Comment by jmesserli** [comment]
*It is fancier if everything is implemented, sure. /kappa*

We can even take the TT one later if you guys like but otherwise it looks good to me. Let's see what @M4R1KU thinks tomorrow.

**Comment by M4R1KU** [comment]
I think that the update functionality on the manage-ui and task-ui has quite a low priority. It's not really a very important feature to me.
Especially when we want to add new features like marks in the next time.

What is very important to me atm is that we can ensure that our existing features do not bug like hell.
We should really take care about this now and not after we have implemented a lot more features.

My roadmap would look like:

- Marks
- Timetable
- Exams
- here it doesn't really matter atm

**Comment by needToRoll** [comment]
Ok I agree on the update functionality thing for the manage Ui. But I disagree for the tasks...
It must be possible to update them otherwise it is the UX of hell. 
If we add updateing in the manage UI later we should hide the option in the UI.

Next Question: 
Do we really need a wiki for the roadmap?
This repo is over administrated anyway...

**Comment by jmesserli** [comment]
Yes I think it would be good to document stuff like this because the human brain doesn't work like a hard disk in that it remembers every detail.
