### ISSUE TITLE
Mark stories as done

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#111]
...

**Comment by needToRoll** [comment]
done, see:
[tsv](https://github.com/outcobra/docs/blob/master/usecase/userstory/userstories.tsv)
[csv](https://github.com/outcobra/docs/blob/master/usecase/userstory/userstories.csv)

**Comment by jmesserli** [comment]
I see you fixed the csv, I think we can remove the tsv now. There is no point in having redundancy right?

**Comment by needToRoll** [comment]
you are right
