### ISSUE TITLE
Finish 1st Meetup Wiki Page and Tasks

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#113]
The conclusion and a task summary needs to be written.

**Comment by jmesserli** [comment]
I added a task overview, please check your assignments @needToRoll @M4R1KU

**Comment by M4R1KU** [comment]
What is missing here?

**Comment by needToRoll** [comment]
It seems to me like this should be closed or adapted to the second meeting.

**Comment by jmesserli** [comment]
No it just needs to be done.

**Comment by jmesserli** [comment]
Apart from the fact that you can just [look at the wiki page](https://github.com/outcobra/outstanding-cobra/wiki/First-Outcobra-Meetup-26.-January-2017), it's the docs that need updating (as I also mentioned at the meetup). I will update the page as soon as I am done. Can't do everything at once.
