### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#115]
We should choose a license which allows us to be safe with our code and how we use it.

The license needs to:
- [ ] Prohibit commercial use
- [ ] Allow the contributions to be used in any way by any team member
- [ ] add your own...

Also, we should write a CLA which is similar to [Apache's](https://www.apache.org/licenses/icla.txt). Maybe we can use theirs.

@outcobra/developers

**Comment by jmesserli** [comment]
I would like to discuss this at a meetup, there are several factors playing into this. Removing it from this sprint for now.

**Comment by M4R1KU** [comment]
Good idea but we should prepare some possible licenses with their advantages and disadvantages and then discuss them at a meetup (if we want to use an already existing one).
