### ISSUE TITLE
Responsive design: Task UI

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#117]

**Comment by needToRoll** [comment]
Does anyone have an idea how this is supposed to look like afterwards?

**Comment by M4R1KU** [comment]
It should not change a lot. Probably you only have to move the filter anywhere else and make sure that word.-wrappings do not look like a piece of shit.

**Comment by needToRoll** [comment]
@M4R1KU I have a "code Style" question... I have a button that simply sets a boolean value.
Should I create a function (TS) or do it directly inside the component (HTML)?

**Comment by M4R1KU** [comment]
I prefer TS

**Comment by needToRoll** [comment]
ok TS it is
