### ISSUE TITLE
Implement responsive design for the whole application

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#120]
Our webinterface needs to be made mobile friendly.

This means the following pages need to be made responsive:
- [x] Manage UI
- [x] Task UI
- [x] Welcome screen
- [x] Login screen (verify)
- [x] Marks UI

**Comment by M4R1KU** [comment]
How do we want to make our MockUps?

**Comment by jmesserli** [comment]
Do you mean tool-wise?

**Comment by M4R1KU** [comment]
Yep @jmesserli

**Comment by jmesserli** [comment]
I don't know, whatever one wants to use or is comfortable with :)

**Comment by M4R1KU** [comment]
The problem is that i can't find a good and free tool for mockups that doesn't restrict one too much.

**Comment by M4R1KU** [comment]
You can find the basic MarkUI [here](https://github.com/outcobra/outstanding-cobra/wiki/MockUps#mark-ui).

**Comment by needToRoll** [comment]
Can you please advise us what to do @M4R1KU?

**Comment by M4R1KU** [comment]
As you can see in the description of the issue the only two UIs that exist which we really need to work on are the Manage UI and the Task UI.
I began with thr Manage UI yesterday so then there is only tbr Task left to work on currently.

**Comment by needToRoll** [comment]
Do you want to keep this issue open @outcobra/developers ?
IMO it is not necessary because we have refactored everything "old"
