### ISSUE TITLE
Assure browser compatibility

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#121]
While implementing responsive design, we are going to check browser compatability with Chrome, Firefox and Edge. If there are big ugly things, we should try to fix them. 
We are focussing on modern browsers and do not support IE.

**Comment by M4R1KU** [comment]
Should we block IE completly or do we just don't care about it?

**Comment by jmesserli** [comment]
We could maybe show one of those "Upgrade your browser" things?

**Comment by jmesserli** [comment]
See: http://outdatedbrowser.com/en/how

**Comment by needToRoll** [comment]
Well I just opend up our tool in Edge...
![image](https://cloud.githubusercontent.com/assets/22860045/23101586/472daf92-f697-11e6-8f55-8d9735107bd1.png)

**Comment by M4R1KU** [comment]
Animations do not work in Edge currently. I think we can live with this. Are you also okay with that? @outcobra/developers 

[Web Animations API](http://caniuse.com/#feat=web-animation)

**Comment by M4R1KU** [comment]
@needToRoll Test on different browser and write bugs as comments here. Or can you can also create new issues if you want.

**Comment by needToRoll** [comment]
Datepicker is acting cringe on mobile (iPhone, Safari)

**Comment by M4R1KU** [comment]
How about an image?

**Comment by M4R1KU** [comment]
Btw everything is behaving cringe on iPhone/Safari

**Comment by jmesserli** [comment]
Mobile Safari seems to not support a property we are using: #178

**Comment by M4R1KU** [comment]
Yeah because it's a piece of shit.

**Comment by jmesserli** [comment]
'course it is.

**Comment by M4R1KU** [comment]
But first @needToRoll the datepicker is not behaving cringe on iPhone/Safari. It's the same as on each other platform. Safari does not treat our datepicker different to other browsers. It's just no optimized for mobile.
But in the next @angular/material a datepicker should be included and from then on we are going to use the new datepicker.

**Comment by jmesserli** [comment]
Apart from the datepicker, are there any other problems or is this done @needToRoll ?

**Comment by M4R1KU** [comment]
Didn't we say this is an ongoing issue and will not or never be done completely?

**Comment by jmesserli** [comment]
Could be, but in that case does it really make sense to have an issue that exists for years? :joy:
I suggest adding this to a "QA-checklist" that could be pulled out in every QA sprint, how does that sound?

**Comment by M4R1KU** [comment]
You are right this makes no sense and I wasn't happy neither. Where do you wanto to put this QA-Checklist?

**Comment by jmesserli** [comment]
The wiki I guess

**Comment by M4R1KU** [comment]
[Wiki page](https://github.com/outcobra/outstanding-cobra/wiki/Browser-compatibility) created
