### ISSUE TITLE
Add Spring Caching and some Cache implementation

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#128]
We should prepare a caching implementation that can be used with Spring's Caching abstraction so that we can just use it whereever we please.

@outcobra/developers What implementation should we use?

**Comment by needToRoll** [comment]
For what reason would you do your own implementation if you can just simply use the default implementation?

I added the default caching for the repo-locator btw

**Comment by M4R1KU** [comment]
There are many built-in implementations to use. I think @jmesserli wants to decide which them we want to use.

**Comment by jmesserli** [comment]
You are absolutely right @M4R1KU since I stated exactly that in the description of the issue.

See this for a list of supported implementations: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#_supported_cache_providers
My preference would be [Ehcache 3](http://www.ehcache.org/documentation/3.2/) since it is supported and has a decent documentation.

**Comment by M4R1KU** [comment]
https://www.mkyong.com/spring/spring-caching-and-ehcache-example/

**Comment by jmesserli** [comment]
This is for Ehcache 2 which does not support the java cachning api. I
believe with ehcache 3 it's a bit different.

Mario Kunz <notifications@github.com> schrieb am Di., 21. März 2017, 12:22:

**Comment by jmesserli** [comment]
See this for a Spring Boot & Ehcache 3 tutorial:
http://www.ehcache.org/blog/2016/05/18/ehcache3_jsr107_spring.html

Joel <jmjmjm439@gmail.com> schrieb am Di., 21. März 2017, 23:17:

**Comment by M4R1KU** [comment]
I think we want to do this before we start with a new Feature.

**Comment by jmesserli** [comment]
Imo this has a low impact on the product right now and I think we should focus on reaching our Sprint commitments

**Comment by M4R1KU** [comment]
Still does not work for me

**Comment by needToRoll** [comment]
It works

**Comment by M4R1KU** [comment]
WTF

**Comment by M4R1KU** [comment]
IF IT WORKS THEN EXPLAIN ME WHY IT DOES NOT WORK ON MY MACHINE

**Comment by needToRoll** [comment]
Ok this seems to act really strange, because it is working if i use postman to make the requests but not over the frontend

**Comment by M4R1KU** [comment]
And we do not use EhCache atm
