### ISSUE TITLE
Add Sentry error reporting

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#129]
There is a Sentry instance available at https://sentry.peg.nu/. The instance already has an outstanding-cobra project with a public DSN of `https://9698caf7ea4b4ea0a115d2c7fa270176@sentry.peg.nu/4`.
For the private DSN (backend) contact me. I'll be moving Sentry to https://sentry.pegnu.cloud/ with docker where I'll create accounts for all of you.

See: https://docs.sentry.io/clients/javascript/integrations/angular2/#angular-cli

**Comment by jmesserli** [comment]
The new instance is set up at https://sentry.pegnu.cloud. You should have received invites to create accounts. The new public DSN is `https://07994a35a96f4713a3d69f15b968997c@sentry.pegnu.cloud/2`

**Comment by needToRoll** [comment]
This can be closed I think

**Comment by needToRoll** [comment]
This can be closed I think
