### ISSUE TITLE
@Bean method AppConfig.getAuth0Config is non-static and returns an object assignable to Spring's ...

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#134]
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/2/

```
Stacktrace (aktuellster Aufruf als erstes):

    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
    at outcobra.server.config.AppConfig$$EnhancerBySpringCGLIB$$7594060f.getAuth0Config(<generated>)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)

@Bean method AppConfig.getAuth0Config is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
```

**Comment by needToRoll** [comment]
Within my current knowlage we can not resolve this issue if we continue using kotlin for this config class.
Plus, this is not a bug, everything works fine. It is just some sort of waring that inner annotation proccessing might not work.

To quote the Error-Message: "This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class."

**Comment by jmesserli** [comment]
https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#static-methods

needToRoll <notifications@github.com> schrieb am Sa., 11. Feb. 2017, 18:59:

**Comment by needToRoll** [comment]
If you are pointing at the companion object option... this is impossible because we need the values from the super class.

**Comment by jmesserli** [comment]
What super class? AuthConfig is perfectly static and doesn't use anything outside of the class.

**Comment by jmesserli** [comment]
I mean AppConfig
