### ISSUE TITLE
Deployment & Release 1.1.0

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#135]
We need a deployment with all the changes that we've made in this sprint. This might include going from war to jar which in turn means setting up a docker image.

**Comment by M4R1KU** [comment]
Do this after the responsive design sprint.

**Comment by M4R1KU** [comment]
When do you want to release 1.1.0?

**Comment by jmesserli** [comment]
I don't know but now that it's basically changing a number and pressing a button I can do it anytime.
