### ISSUE TITLE
Implement request authentication on service-level

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#136]
Because our attempt to fix the request filter failed, we decided to implement request authentication on service-level. 
This will make #67 obsolete

**Comment by jmesserli** [comment]
Are you sure you can do this in sprint 8? I'd move this to sprint 9 as we have to prolong it anyways.

**Comment by needToRoll** [comment]
The request validation has been implemented.
Only the tests are still open/TODO. 
A review would be a good thing as well!
