### ISSUE TITLE
httpBasicAuth does not work

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#137]
I booted the server with the development profile and tried to access the api.
![image](https://cloud.githubusercontent.com/assets/22860045/22857399/a0eb5384-f0a4-11e6-9c62-1c8b27d3917a.png)

**Comment by needToRoll** [comment]
this only affects backend development, therefore the priority is not as high as expected

**Comment by M4R1KU** [comment]
Does this still not work?

**Comment by M4R1KU** [comment]
@needToRoll update?

**Comment by M4R1KU** [comment]
This should work with the correct profile enabled...or am I wrong? @needToRoll

**Comment by needToRoll** [comment]
Last time I checked it did not... and the profiles were enabled

**Comment by M4R1KU** [comment]
I accidently pushed it to develop but it is fixed now.
