### ISSUE TITLE
Migrate current MockUps to Adobe Experience Design

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#146]
We change our MockUp tool to the new Adobe Experience Design because most of us have already a CreativeCloud subscription, so we don't have to buy a new tool and currently it looks much more promising  (regarding the beta state) than MockFlow did.

**Comment by jmesserli** [comment]
I don't understand the current mock ups, so I'm not ready to migrate them.

**Comment by M4R1KU** [comment]
Do you have questions that need to be answered?

**Comment by jmesserli** [comment]
Yeah

**Comment by M4R1KU** [comment]
So then ask them

**Comment by M4R1KU** [comment]
We have some templates on AXD but the current mockups will not be migrated since we decided not to use them.
