### ISSUE TITLE
Implement better error handling (Backend)

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#150]
Some time in the future we want to have a better and more generic way to handle errors in the backend(send i18nKeys etc.)

**Comment by M4R1KU** [comment]
ping @needToRoll

**Comment by needToRoll** [comment]
Why is this suddenly such a high priority thing?

**Comment by M4R1KU** [comment]
#169 is kind of depending on this better error thingy.
The important part of this issue is to provide a better response when an error occurs (i18nkey etc.) and that is very important to me.

**Comment by jmesserli** [comment]
The pull-request for this seems to have vanished (if there was one). What is left to be done here? @needToRoll

**Comment by needToRoll** [comment]
reformat code according the new style and reopen the PR

**Comment by jmesserli** [comment]
Great, could you please do that? :)

**Comment by needToRoll** [comment]
Yea now I can...

**Comment by M4R1KU** [comment]
Open PR please.

**Comment by needToRoll** [comment]
@M4R1KU why did you reference #169 here? do you want to add failsafe for this scenario?

**Comment by M4R1KU** [comment]
The error in #169 only exists because the error in the observable is not catched. And I wanted to show a good error notification and not a bullshit generic error message. So I wanted better error handling and after that is implemented we fix it on the frontend and then #169 will be resolved.
