### ISSUE TITLE
Automated deployment

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#151]
I can set up automated deployment using semaphore, circle ci or travis. I'd prefer doing it with Semaphore because I can easily add configuration files that will be present during the deployment. In addition, Semaphore is tamper-proof since one can't just change a file in the repository and potentially execute commands on the server side.
I can do it with all of them though. You guys choose @outcobra/developers 

This depends on #68 #140 and fixes #135

**Comment by needToRoll** [comment]
according to our wiki you are responsible for the tooling stuff... you should choose!

**Comment by jmesserli** [comment]
Ya look I said that I'd choose Semaphore but I heard that certain people don't like Semaphore at all @M4R1KU   *cough*

**Comment by M4R1KU** [comment]
@jmesserli Do what you want bc you are the tooling guy. I just prefer CircleCI or TravisCI. But which of the three CIs we currently have does make the deployment doesn't really matter. Speed does not really matter either in my opinion.

**Comment by jmesserli** [comment]
Yeah I think that we should ditch at least one CI, three of them is definitely not needed.

**Comment by jmesserli** [comment]
My votes:
1. Circle
2. Travis
3. Semaphore

**Comment by needToRoll** [comment]
My votes:
1.Circle
2.Travis
3.Semaphore

**Comment by jmesserli** [comment]
Imo we can remove Circle and Travis, you guys can still edit the Semaphore build as I added you both to the organisation on there. Or does that hurt anyone's feelings? :P

**Comment by M4R1KU** [comment]
yeah here :( :(

**Comment by jmesserli** [comment]
You want to keep Circle right? @M4R1KU

**Comment by M4R1KU** [comment]
Or travis :joy:

**Comment by jmesserli** [comment]
choose, one of them has to go :joy:

**Comment by needToRoll** [comment]
according to the votes travis should stay... let go of circle @M4R1KU
