### ISSUE TITLE
Colorpicker picks random color

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#160]
When a user clicks on "cancel" in the color picker (tested on "add new subject"), a random color is picked instead of canceling the picking.
Is this intended behavior?

**Comment by M4R1KU** [comment]
Yes this behaviour is intended as far as I remember.

**Comment by jmesserli** [comment]
It's a bit weird if you've picked a color before, open the color picker
again and click cancel, that it then picks one randomly. Imo

Mario Kunz <notifications@github.com> schrieb am Fr., 17. März 2017, 16:08:

**Comment by M4R1KU** [comment]
Let's discuss the wanted behaviour. @jmesserli @needToRoll
