### ISSUE TITLE
Manage UI swiping is reversed

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#162]
When you are on mobile (tested in Firefox's Responsive Design Mode & Nexus 5) on the manage ui and swipe from right to left, it goes to the left instead of to the right as expected.

Related to #157

**Comment by M4R1KU** [comment]
HammerJS behaves very cringy (even on their website) when I try to swipe.
I'd say won't fix.

**Comment by jmesserli** [comment]
@M4R1KU so no swiping at all?

**Comment by M4R1KU** [comment]
Currently not I'd say. It's not that important.

**Comment by jmesserli** [comment]
We could also try https://zingchart.github.io/zingtouch/
but I agree that it's not important. You also need to remove the hammerjs dependency in this case.
