### ISSUE TITLE
autoloading does not work after creating a class

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#166]
After creating a class, the user can only see the new class.
![bug1](https://cloud.githubusercontent.com/assets/22860045/24079380/e690da14-0c86-11e7-9335-35ed52c8333e.png)

![bug2](https://cloud.githubusercontent.com/assets/22860045/24079381/e6922342-0c86-11e7-952f-e90484189e71.png)

![bug3](https://cloud.githubusercontent.com/assets/22860045/24079379/e68ca1d8-0c86-11e7-98d6-6bfae5a75a15.png)

![bug4](https://cloud.githubusercontent.com/assets/22860045/24079378/e68c3da6-0c86-11e7-9963-161ea9abe6ea.png)

**Comment by jmesserli** [comment]
Closed in #157
