### ISSUE TITLE
Choose Components and Services to be tested

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#171]
We need to choose our most important components and services that need to be tested.

**Comment by jmesserli** [comment]
Does this need to be documented anywhere?

**Comment by M4R1KU** [comment]
Of course this must be documented.

**Comment by jmesserli** [comment]
I'll create a wiki page then.

Mario Kunz <notifications@github.com> schrieb am Sa., 25. März 2017, 14:05:

**Comment by jmesserli** [comment]
Created a wiki page [here](https://github.com/outcobra/outstanding-cobra/wiki/Frontend-Testing)

**Comment by M4R1KU** [comment]
You can find the selected components on the mentioned wiki page.
