### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#172]
Implement tests for the choosen components and tests.

This includes creating mock services.

**Comment by needToRoll** [comment]
I would like to contribute but I need an introduction...

**Comment by M4R1KU** [comment]
We can sit together tomorrow or you learn it by your self. There are plenty
good tutorials in the World Wide Web and the official documentation is very
helpful. Just google it....

needToRoll <notifications@github.com> schrieb am Di., 2. Mai 2017, 21:26:

**Comment by needToRoll** [comment]
I meant what exactly you wan't to do, approaches, best practices, ideas... that kind of stuff

**Comment by M4R1KU** [comment]
I would also be happy to know that tbh.

**Comment by needToRoll** [comment]
Lets sit together and define that... @jmesserli will you join us?

**Comment by M4R1KU** [comment]
Meetup decison: this is no longer necessary as the tests wouldn't add much value as it is now.
