### ISSUE TITLE
Make all tests pass

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#173]
We should make all tests pass even if they do not have any valuable test logic.
This is mostly fixing the dependency injection
Another option is to remove the tests.

**Comment by M4R1KU** [comment]
This is finished so removing in progress.

**Comment by jmesserli** [comment]
Frontend build is failing on Jenkins https://ci.pegnu.cloud/blue/organizations/jenkins/outcobra%2Foutstanding-cobra/detail/feature%2F%23173-make-all-tests-pass/6/pipeline

**Comment by jmesserli** [comment]
I tried to merge develop but apparently that resulted in a big pile of crap. @M4R1KU could you possibly merge this as you know changes in the frontend refactoring better?

**Comment by M4R1KU** [comment]
lol @jmesserli 😂
Tomorrow....
