### ISSUE TITLE
Route is not preserved when logging in

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#187]
If I visit https://outcobra-a.pegnu.cloud/manage in a logged-out state, I end up on / after logging in.

**Comment by M4R1KU** [comment]
How do we want to handle this? With the lock it seems to be quite hard because it redirects you multiple times. We should do this when we replace auth0 (if we do) or when we build our custom login ui.

**Comment by jmesserli** [comment]
So the lock is the problem at the moment?

**Comment by M4R1KU** [comment]
Yes I already coded it the way that it should work but the lock is redirecting weird...

**Comment by jmesserli** [comment]
Okay then we'll do it when we build our custom ui, I don't think moving away from Auth0 at this moment is the right thing to do.

**Comment by M4R1KU** [comment]
I think the same way and it does not make sense to do this now if we replace the lock anyways.

**Comment by jmesserli** [comment]
Can we maybe do a temporary solution with local storage?

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
