### ISSUE TITLE
Fix dialogs

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#195]
We need to fix the dialogs sizing (on mobile) and we should that there is no weird overflowing and such things that break the UX.

- [x] buttons are overflowing 
    https://cloud.githubusercontent.com/assets/613138/25145386/5a79d37a-2471-11e7-80ed-b4620354b5eb.png
- [ ] Manage UI dialogs do not align correctly on mobile
- [x] where do we want to  place the dialogs on mobile?

**Comment by jmesserli** [comment]
Imo the dialogs are bad at the top because users with big displays need to do weird movements to reach them. I'd put them in the middle because bottom probably looks bad.

**Comment by M4R1KU** [comment]
Agreed

Joel Messerli <notifications@github.com> schrieb am Do., 20. Apr. 2017,
01:11:

**Comment by jmesserli** [comment]
What's the estimate on this (story points)?

**Comment by M4R1KU** [comment]
I consider this done.
