### ISSUE TITLE
Define agenda items for next meetup

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#200]
The next meetup will be on the 2017-04-29 at 15:00 at a TBD place.

To prepare for this meetup we need to fix our agenda items.
This means:
- [x] Creating a [wiki page](https://github.com/outcobra/outstanding-cobra/wiki/Second-Outcobra-Meetup-29.-April-2017) for the agenda items
- [ ] Discussing on this issue, what we want to discuss at the meetup
- [ ] Update wiki page

**Comment by jmesserli** [comment]
- Sprint Planning

**Comment by M4R1KU** [comment]
* Caching
* All the small issues which are every fucking where

**Comment by M4R1KU** [comment]
* Materializecss

**Comment by M4R1KU** [comment]
* Colorpicker behaviour

**Comment by needToRoll** [comment]
- licence

**Comment by needToRoll** [comment]
- releases (How often)

**Comment by needToRoll** [comment]
- Closed Beta 08.2017?

**Comment by needToRoll** [comment]
The second meetUp is over so this can be closed

**Comment by needToRoll** [comment]
The second meetUp is over so this can be closed
