### ISSUE TITLE
Missing Jenkins permission

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#205]
![image](https://cloud.githubusercontent.com/assets/22860045/25556903/4ed36c8c-2d06-11e7-9d1a-987b5e30d1fe.png)
Is this a joke?

**Comment by needToRoll** [comment]
It would be nice to see if my suff builds or not

**Comment by needToRoll** [comment]
Is this a related problem?

![2017-04-29 18_49_02-amend_poper error handling by needtoroll pull request 204 outcobra_outstand](https://cloud.githubusercontent.com/assets/22860045/25557190/b5b91c52-2d0c-11e7-9881-c509dadda0c0.png)

**Comment by jmesserli** [comment]
You should have the permissions now. Next time chill and write to me instead of opening such a useless issue with rethoric questions.
