### ISSUE TITLE
TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#216]
When I flip the language, this happens:

https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/80/

```
TypeError: setting a property that has only a getter
  at nodes (./src/$_gendir/app/app.component.ngfactory.ts:936:14)
...
(45 additional frame(s) were not displayed)
```

**Comment by M4R1KU** [comment]
Why me? It's such a trivial problem. I am not the only one who can fix this.

**Comment by jmesserli** [comment]
You don't have to do it, I just usually assign somebody
