### ISSUE TITLE
TypeError: Die Eigenschaft "initialNavigation" eines undefinierten oder Nullverweises kann nicht abgerufen w...

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#217]
Happens only in IE on page load

https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/82/

```
TypeError: Die Eigenschaft "initialNavigation" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
  at t.prototype.isLegacyDisabled (~/@angular/router/@angular/router.es5.js:5968)
  at Anonymous function (~/@angular/router/@angular/router.es5.js:5905)
  at t.prototype.invoke (~/zone.js/dist/zone.js:363)
  at onInvoke (~/@angular/core/@angular/core.es5.js:4125)
  at t.prototype.invoke (~/zone.js/dist/zone.js:363)
...
(8 additional frame(s) were not displayed)
```

**Comment by M4R1KU** [comment]
AFAIK this is because IE does not know the object which contains the initialNavigation thingy.
Probably this needs just a null-check to ignore it in IE then.

**Comment by needToRoll** [comment]
according to [this](https://github.com/angular/angular-cli/issues/5762) the simplest way would be to disable aot...

**Comment by M4R1KU** [comment]
Impossible. The angular/cli only works with aot (ng build --prod is in fact
AOT) so to "remove" AOT would mean to remove the angular/cli and that would
be absolutely ridicoulus when in fact the problem only exists on one shitty
browser.

needToRoll <notifications@github.com> schrieb am Mi., 3. Mai 2017, 22:19:

**Comment by needToRoll** [comment]
Well: "Workaround which is working for me is to disable aot in build which is enabled by default. Then my APP_INITIALIZER works fine in IE. You can do it by adding -- aot false to the build command.
e.g. ng build --prod --aot false"

**Comment by jmesserli** [comment]
Yeah we're not disabling AOT. But there seems to be another fix the comment just below: https://github.com/angular/angular-cli/issues/5762#issuecomment-295670906

**Comment by M4R1KU** [comment]
https://github.com/angular/angular/issues/15501 This is the more accurate issue bc it is not an issue of the cli rather of angular itself. As it seems it only exists in angular 4.0.0 and above. We could test the workaround and wait for the next releases of angular.

Worst case would be to go back to angular 2.4.5 or so. Disabling AOT is not really an option for me personally.
