### ISSUE TITLE
Delete manage-entities with tasks, marks etc.

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#222]
How do we want to handle the deletion of manage-entities if one of their child subjects has tasks, marks etc. that belong to it? Currently we get an SQL error because DataIntegrityViolation

**Comment by jmesserli** [comment]
On delete cascade

**Comment by needToRoll** [comment]
I agree with @jmesserli. We should allow the user to delete the entity.
So this issue turned into an enhancement.

**Comment by M4R1KU** [comment]
Without noticing the user that those things will be lost?

**Comment by jmesserli** [comment]
The ui has a very specific confirmation message.

**Comment by M4R1KU** [comment]
It does no include that

**Comment by jmesserli** [comment]
Oh yeah I was thinking of something else. Still think the children should be removed, we can add the information to the dialog.

**Comment by M4R1KU** [comment]
Add it in every case or only when there are relations?

**Comment by jmesserli** [comment]
Maybe only when there are relations otherwise the user could be scared (what other things are being deleted when i remove this task??).

**Comment by needToRoll** [comment]
The second would be nice... but not easy to do I guess.

**Comment by jmesserli** [comment]
But I wouldn't query the database for that

**Comment by needToRoll** [comment]
It will be hasrd to do without I think ;-)

**Comment by M4R1KU** [comment]
How do it then?

**Comment by jmesserli** [comment]
Then I was not clear enough. Only show such a message when the entity 'can' have relations.

**Comment by M4R1KU** [comment]
So only if there is a subject in the tree? (for the current situtation)

**Comment by jmesserli** [comment]
No I mean let's say entity X has no children, then the message for deleting X should not contain an info that all children will be deleted too. (This might be obvious already).

**Comment by jmesserli** [comment]
(*Entity X technically _can't_ have children)

**Comment by M4R1KU** [comment]
Do you have a real world example of that entity X

**Comment by jmesserli** [comment]
Task has no children e.g.

**Comment by M4R1KU** [comment]
That's true but task is not a manage-entity

**Comment by jmesserli** [comment]
Join discord :P

**Comment by jmesserli** [comment]
Conclusion:
* We will be adding a count to the delete dialog (This deltes x classes, y tasks, z exams, etc.) 
* This is a lowest-priority feature as the business value is very small.
* For now, on delete cascade will be the solution

**Comment by jmesserli** [comment]
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/92/
