### ISSUE TITLE
Change effort datatype from int to double

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#237]
I find it odd that the effort for a task has to be an integer.
A task that takes 0.5 or 1.5 hours is a very likely scenario.

I think this should be changed!
What do you think @outcobra/developers?

**Comment by needToRoll** [comment]
![image](https://cloud.githubusercontent.com/assets/22860045/26321715/3ccd19f0-3f28-11e7-8046-be3e1101c81f.png)
Minutes or hours what do you prefere?

**Comment by jmesserli** [comment]
Exactly what it says, (rendered as) hours on the frontend, minutes on the backend
