### ISSUE TITLE
1.1 Institutionen erstellen

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#24]
Ich als Benutzer kann eine Institution (Schule) IET-GIBB erstellen.

Die Schule IET GIBB wird in der Datenbank gespeichert

- [ ] Dto definieren
- [x] Endpoint definieren
- [x] Service implementieren

**Comment by needToRoll** [comment]
@jmesserli, @M4R1KU  i need help to manage the Spring/Kotlin interaction

**Comment by jmesserli** [comment]
@needToRoll I'll be there in about an hour.

**Comment by needToRoll** [comment]
@outcobra/developers can someone take over the DTO part? I am not sure if I would do it correctly
