### ISSUE TITLE
Task UI does not scroll

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#242]
![grafik](https://cloud.githubusercontent.com/assets/613138/26494696/37022d4e-4220-11e7-9bfe-26c131c699dc.png)
As you can see, the footer is not visible because the content of the page is not scrolling itself.
Maybe this affects other pages too.

**Comment by M4R1KU** [comment]
Which environment?

**Comment by jmesserli** [comment]
This is in prod

**Comment by M4R1KU** [comment]
outcobra-a.pegnu.cloud?
Browser?

**Comment by jmesserli** [comment]
Yes we don't have another prod, Firefox and Edge seem to be affected, it works fine in Chrome

**Comment by M4R1KU** [comment]
Happens to me in firefox only

**Comment by jmesserli** [comment]
The "content" does not scroll, it has no scrollbar. The whole site scrolls, sure.

**Comment by jmesserli** [comment]
![grafik](https://cloud.githubusercontent.com/assets/613138/26494973/b868287e-4221-11e7-9d93-dd602fb513d5.png)

**Comment by M4R1KU** [comment]
I have no fucking idea why this does not work. Firefox is shit to debug and behaves just weird.

**Comment by M4R1KU** [comment]
Because the task ui is now refactored this is fixed
