### ISSUE TITLE
Fix actuator endpoints

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#247]
I can't access most of the actuator endpoints when running without basic auth activated.

**Comment by jmesserli** [comment]
That is intended and has been this way forever as far as i know. Randoms should not be able to do a thread dump in prod e.g.

**Comment by needToRoll** [comment]
I am with @jmesserli on this one

**Comment by M4R1KU** [comment]
But they are all useless if we cannot see them in dev.
And I never talked about prod.

**Comment by needToRoll** [comment]
If you need the informations just activate the profile

**Comment by jmesserli** [comment]
What do you mean?

**Comment by M4R1KU** [comment]
But then the frontend is useless

**Comment by jmesserli** [comment]
We can probably reconfigure this for dev though: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-security-actuator
