### ISSUE TITLE
Discuss exam-task usage

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#256]
To implement the exam feature I need to know how we are going to use the exam-task entity.
In my opinion there are two possible ways.

1. Learning goals, the content of the exam.
2. A task to learn for the test.

I prefer the first option. (Otherwise the entity should be merged with the task-entity)
What do you think @outcobra/developers?

**Comment by M4R1KU** [comment]
Why do you prefer the first one?
I'd the second one which is linked (on the UI) to the exam itself or contains the information of the exam(on the UI).

**Comment by needToRoll** [comment]
We can easily create the possibility to link a normal task to a exam but we need the abillity to list the task content.

**Comment by needToRoll** [comment]
And if we implement the second option I am not sure if we need the entity we can just add an optional exam id to the task-entity

**Comment by M4R1KU** [comment]
We should not discuss technical things in the first place imo instead focuss on what's better for the user

**Comment by M4R1KU** [comment]
Yeah that's true.
I think that my first answer is bs.

**Comment by needToRoll** [comment]
The first option it is...
