### ISSUE TITLE
Orientation checking is broken

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#257]
The detection of the current orientation of the window is broken in many "old" browsers because every fucking company had the feeling that they should use their own fucking solution in their browsers (rant end)

related to https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/138/

**Comment by jmesserli** [comment]
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/137/

**Comment by jmesserli** [comment]
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/143/

**Comment by jmesserli** [comment]
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/142/
