### ISSUE TITLE
Add description to exam?

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#258]
It seems like the exam does not have a description jet.
In my opinion it should. The user needs an way to store additional information.

What do you think @outcobra/developers?

PS: Should I put the DB change into the create script or into a new migration file?

**Comment by M4R1KU** [comment]
Most likely it should have one. But an optional

**Comment by jmesserli** [comment]
We can add an optional description. Never put db changes in the create script, you'll break all environments after development.
