### ISSUE TITLE
Naming Schemes

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#259]
We need naming schemes for our servers and also the subdomains for our new domains.

I proposed that we use planets for our servers, where the closeness to the sun signifies the "prodyness".

1. Mercury - Most Prod
2. Venus
3. Earth
4. Mars
5. Jupiter
6. Saturn
7. Uranus
8. Neptune - Least Prod

@M4R1KU Suggested that we use the moons of neptune

For the subdomains, I'd suggest `staging` for what is now known as `outcobra-a` and then no subdomain for prod obviously.

Also, what mailboxes do we need? `support`, `info`, maybe each of our names, any others?

**Comment by M4R1KU** [comment]
For the moons of neptune we could take the diameter or the mass as measure for the "prodyness".

1. Triton (prod)
2. Proteus
3. Nereid
4. Larissa
5. Galatea
6. Despina
7. Thalassa
8. Naiad (least prod)
There are more moons but we shouldn't need more than 8 environments.

**Comment by needToRoll** [comment]
Reguarding the names I don't care... both options are all right.
How about we use planets for servers and moons for environements

Emails:
- [x] support (users asking for help)
- [x] info (@outcobra/developers contacting their customers)
- [x] names (direct contact)
- [ ] bug (might be nice as well)

**Comment by jmesserli** [comment]
So you would be okay with e.g. `nereid.outcobra.school` for the staging? (This would in turn point to the server `earth.outcobra.cloud`)
Or did I not understand that correctly?

Maybe also security@ for the mails.

**Comment by needToRoll** [comment]
After giving it a second thought this might not have been the best idea.
If I would have to choose I would go with @M4R1KU's scheme.

I think adding security@ to our emails is a greate idea.
It would be:
- [x] support (users asking for help)
- [x] info (@outcobra/developers contacting their customers)
- [x] names (direct contact)
- [x] bug (bug reports)
- [x] security (speeks for itself)

**Comment by jmesserli** [comment]
Mailbox + Cloudflare is set up. I'll share the logins with you personally.
