### ISSUE TITLE
Beta Preparation

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#262]
In the naming scheme issue we discussed the emails we want for users contacting us and the other way.

We should make a list of things that need to be done before the beta and are not core features.
The naming scheme and email thing are both two points. But what are the others.

Discuss it here and then place it on [this](https://github.com/outcobra/outstanding-cobra/wiki/Beta) wiki page.

We should have in mind that @jmesserli won't be available most of july.

**Comment by needToRoll** [comment]
'

**Comment by needToRoll** [comment]
- [ ] Logo 
- [ ] Meeting with DG BIT
- [ ] Create "About-Pages"
- [ ] Define bug-bounty content
- [ ] Prepare beta presentations
- [ ] Define concrete list with contacts to recrute beta testers
    - [ ] Prepare communications
- [ ] Print cards'

**Comment by jmesserli** [comment]
Beta is going :)
