### ISSUE TITLE
MarkGroup Update

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#263]
I am currently having some trouble implementing the MarkGroup update functionality. Especially the removal of marks in the group.
The problem is that I can't say the backend to remove a list of marks from the group.

So how should I implement it?
@needToRoll @jmesserli

**Comment by needToRoll** [comment]
I suggest we take a look at it tomorrow after work... (Maybe sit together shortly)
I don’t have access to my pc tonight.

**Comment by M4R1KU** [comment]
I am not at work.
And you should look what I wrote you on discord last saturday.
