### ISSUE TITLE
Incomplete ExamDto after creation because of resused transaction

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#267]
@needToRoll wrote a comment about a backend bug in the exam.component on line 143 and line 170.

Quick Links:
https://github.com/outcobra/outstanding-cobra/blob/19318030331d308e8188fb658093bb890541c87a/frontend/src/app/exam/exam.component.ts#L143
and
https://github.com/outcobra/outstanding-cobra/blob/19318030331d308e8188fb658093bb890541c87a/frontend/src/app/exam/exam.component.ts#L171

What is this bug?

**Comment by needToRoll** [comment]
The bug is that the ExamTasks are not populated into the Exam entity because the hibernate transaction will  be commited after the webservice call ended. A possible solution would be to save the tasks in a different transaction. (Transaction propagation requires new)
