### ISSUE TITLE
Kotlin / Lombok incompatibility

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#27]
It seems like there is some kind of incomatibility between [Lombok] (https://projectlombok.org/) and [Kotlin] (https://kotlinlang.org/).

It is not possible to access "lombok-generated methods in Kotlin.
Example:
If a Java Class looks like this: 
```Java
@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class Institution {
    @Id
    private Long id;
    @NotNull
    private String name;
    @ManyToOne
    private User user;
    @OneToMany(mappedBy = "institution")
    private List<SchoolClass> schoolClasses;
    @OneToMany(mappedBy = "institution")
    private List<Teacher> teachers;
}
```

I can **not** do this:

```Kotlin
    override fun getInstitutionById(id: Long) : InstitutionDto {
        var institution : Institution = repository.getOne(id)
        return InstitutionDto(institution.id,institution.name)

    }
```
Because id and name are private...

...but if I add this to the Java Class...

```Java
    public Long getId(){ return this.id; }
    public String getName(){ return this.name; }
```
...it works properly

There is a possible workaround here: https://discuss.kotlinlang.org/t/kotlin-java-lombok-interop/1442

**Comment by needToRoll** [comment]
There is an issue about it on YouTrack but it is not verifed yet:
https://youtrack.jetbrains.com/issue/KT-14089

**Comment by M4R1KU** [comment]
Why are you assigning everybody

**Comment by M4R1KU** [comment]
Why are you assigning everybody
