### ISSUE TITLE
Schoolyear from / to weird

### ISSUE THREAD

**Issue by bweben** [outcobra/outstanding-cobra#273]
If you create a new school year with the dates 122 and 1233 it works.
When you edit this school year and change the 1 of 1233 to a 3 it gives the following error messages:
![image](https://user-images.githubusercontent.com/10772590/29188254-dc121ea6-7e12-11e7-8b4a-5c9b691fe4eb.png)

**Comment by M4R1KU** [comment]
Can be fixed by fixing #250 and then adding a pattern validator on the input field to force e certain date pattern.

**Comment by jmesserli** [comment]
Thanks for the report @bweben! :)

**Comment by M4R1KU** [comment]
I think this should work on the current staging version. @bweben do you want to retest?

**Comment by bweben** [comment]
Does work now 👍
