### ISSUE TITLE
Allow use of new domain

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#276]
Make staging.outcobra.school work to access the instance that is only accessible through outcobra-a.pegnu.cloud at the moment.

**Comment by jmesserli** [comment]
It's accessible now, the auth0 redirect url mist be changed in the auth0 dashboard @M4R1KU and in the frontend props

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by M4R1KU** [comment]
Is the backend on staging.outcobra.school/backend or on staging.outcobra.cloud?

**Comment by jmesserli** [comment]
Yes, like before on /backend

**Comment by M4R1KU** [comment]
Okey.
I added it to auth0 and will now add a new frontend environment.

In #259 we defined our server/environment names will they now have impact anywhere?

**Comment by jmesserli** [comment]
Yes the server names are used, staging.outcobra.school points to larissa.srv.ourcobra.cloud for example.

Also we should consider making this dynamic on the frontend side, having to change this statically for each env is a bit annoying.

**Comment by M4R1KU** [comment]
Let's discuss this at the meetup or some other opportunity.

**Comment by jmesserli** [comment]
The new domain can now be used (see 4f54298)
