### ISSUE TITLE
Remove backend-model

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#296]
Since Kotlin and QueryDsl now play along nicely (see [here](https://gist.github.com/zvozin/f46cc9fe1dd00bb648808317e77bf8ca)) we are finally able to remove the backend-model module and have all our entity classes as Kotlin classes.

**Comment by needToRoll** [comment]
I can't get the query dsl classes generated @outcobra/developers can you take a look at it?

**Comment by M4R1KU** [comment]
Fixed it. But look at the link I provided in the description next time.

Other question: Do we remove the backend-model directory now or do we want to keep it for some time?

**Comment by jmesserli** [comment]
Kill it with fire. We trust in git 😄
