### ISSUE TITLE
Staging findings

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#333]
After a quick check on our current develop branch (e8e5974) I have seen a few thing we should fix before pushing it to Nereid.

# needToRoll
- [x] The user can not access the register function from the landing page (there should at least be a register button on the login screen, the back button is confusing)
- [x] Signup is not translated (on "/auth")
- [x] The logout button should redirect to the landing page and not to "/auth" because the user can not navigate to any other page after that. 
- [x] The "register with google"-Button only works on the second attempt.
- [x] The theming does not work
- [ ] The banner on the landing page is too big in my opinion. The design seems too inconsistent.
# jmesserli
- [x] Task UI: Button "Abschliessen" not translated
- [x] Text labels are below the value (e.g. on Task UI)
- [x] "Search" in search bar not translated (e.g. on Task UI)
- [x] Logout not translated
- [x] Theme chooser has weird padding
- [x] Exception handling does not always work on login page (e.g. not signed up error)
- [ ] Markdown has no links on the new startpage; other markdown pages are gone
- [ ] User needs to click on login on the startpage even if he is already logged in
- [x] User not redirected after signup with google (not: only works on the second attempt from above)

I will take a closer look tomorrow and update this issue accordingly. Please comment your findings below.

**Comment by jmesserli** [comment]
I edited some more things into the main issue text. Some of them might be longer-existing problems, which we should fix anyways.

**Comment by M4R1KU** [comment]
User needs to click on login on the startpage even if he is already logged in: What is expected?

Markdown has no links on the new startpage; other markdown pages are gone
and
The banner on the landing page is too big in my opinion. The design seems too inconsistent:
The landing page is only temporary I want to do a better one later where all the information is available and the where the design is finished.

**Comment by jmesserli** [comment]
Already logged in has two options imo:
1. Redirect to "logged-in part" directly
2. Show "Go to app ->" (e.g.) instead of Login button
