### ISSUE TITLE
Staging crash

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#334]
I did a quick analysis of our issues on larissa this morning.
First of all I have implemented a workaround for the AuthFilter problem.
My next step was to run 'ng s' to see what's going on. Everything worked.
It seemd illogical to me that such a small change would affect the whole application.
Therefore I've reverted the previous backend chages, restarted the frontend and it worked.

This is how I found out that the problem is within the production frontend bundle.

But I was unable to find out what (inside the bundle) causes the issue. Do you have any ideas @outcobra/developers?

**Comment by jmesserli** [comment]
Did you try the production build or only the dev build?

**Comment by needToRoll** [comment]
When I run ng s --prod I have the same result as on nereid. Independent of the profile I activate for the backend.

**Comment by M4R1KU** [comment]
The backend should not have any influence on this problem.

**Comment by needToRoll** [comment]
@M4R1KU do you have any ideas why those problems only appear if we "use" the production bundle?

**Comment by M4R1KU** [comment]
Should all work now. I forgot to allow the ping endpoint so this should be the only issue.

**Comment by needToRoll** [comment]
Can you plase allow all requests on /api/ping as well?

**Comment by needToRoll** [comment]
It seems like the url of larissa is not conigured correctly in the google console.
On a side note, could you plaese grant me access on the project, on the google console?

**Comment by jmesserli** [comment]
This is fixed (and everything else is in #333). This can be closed @needToRoll ?
