### ISSUE TITLE
Timepicker

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#34]
We need a timepicker component in material design. It should contain 2 text fields for the minute and the hour and each textfield has 2 button to increase and decrease the number.

When 23 is reached in the hour field then a click on the increase button should increase the number to 0 (same on the other field and in the other direction).

If it is possible the Timepicker should be available as inline element and as a popup too (TimepickerPopupComponent).

**Comment by jmesserli** [comment]
If you're not already on it, I'd like to try and do this ✌️

**Comment by M4R1KU** [comment]
@jmesserli I haven't started yet so feel free to begin. On the frontend-scaffolding branch it already has a timepicker component so you don't have to make a new one.

**Comment by jmesserli** [comment]
Were you looking for something like the most left one?

![image](https://cloud.githubusercontent.com/assets/613138/20032740/6c7d72fe-a391-11e6-8715-ed71e9eb7e06.png)

**Comment by M4R1KU** [comment]
@jmesserli I thought about the most left one but if you think another is better feel free to implement that. 
And it would be awesome if could have a timepicker like the one on android and in the material design docs but I think it is too much work for now.

**Comment by jmesserli** [comment]
@M4R1KU Same, I think the original one is not really needed at this point in time. Also we'd still kind of need to implement the left one because the original one isn't really inline at all.

**Comment by M4R1KU** [comment]
@jmesserli Yeah the original would be a popup like the datepicker currently or a popup in the modal style like on android.

**Comment by jmesserli** [comment]
I suppose this is needed when we start coding the timetable? We should discuss and document our planned schedule for the next few features / epics so that we can plan the issues without milestone. This applies to #33, #67 too. I'll create an issue for this.

**Comment by needToRoll** [comment]
This can be closed because angular-material has announced to release a date- and a time-picker within the next release.
