### ISSUE TITLE
Staging issues #2

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#343]
I did some more testing today and found that the following problems exist:
- [x] When logging in with google, the user is not automatically redirected 
- [x] The start page does not even load (sentry window on white) when `https://apis.google.com/js/platform.js` is blocked by an extension
- [x] Text labels on app info modal are below values
- [x] Label "Fortschritt" on task ui hugs line
![grafik](https://user-images.githubusercontent.com/613138/34761767-5ffac1f6-f5e5-11e7-90d5-4ed67cc3204a.png)
- [x] Description on task is displayed even if empty
(Firefox 57.0.4)

------------------------------------------------------------------------
Additions made by @needToRoll
- [x] Bring back the two missing introduction texts
- [x] I would recommend bringing back the theming before the release (optional)
- [ ] Fix date translations (how hard is this to implement?)

After those are fixed we can do a new release I think.

**Comment by M4R1KU** [comment]
I wont do theming because it never was really good and I don't think many used it and would use it as long as it looks that bad.
Later we can bring it back, but first #340 must be done to do this in an intelligent manner.
