### ISSUE TITLE
Data loaders in .gitignore

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#357]
https://github.com/outcobra/outstanding-cobra/blob/929055a5b841547bc8e0efc44f2b6e5b3d7fa970/.gitignore#L10

Why is the data directory beeing ignored?

**Comment by jmesserli** [comment]
Because https://github.com/outcobra/outstanding-cobra/blob/929055a5b841547bc8e0efc44f2b6e5b3d7fa970/docker-compose.yml#L12
