### ISSUE TITLE
Remove Learning Targets

### ISSUE THREAD

**Issue by MigliS** [outcobra/outstanding-cobra#363]
If I want to add an exam, there's to option to set own learning targets.
Is there no option to remove the accidentally added targets so it's possible to save the exam?
![outcobra-issue](https://user-images.githubusercontent.com/12274029/36308108-74718c62-131f-11e8-9b20-46c411f5d8a5.JPG)

**Comment by jmesserli** [comment]
Thank you for the report @MigliS!
In the new version 1.4 you'll actually be able to delete one by leaving a target empty.
But a delete button would be a good idea imo.

**Comment by M4R1KU** [comment]
I have another idea. The user should be able to add objectives without clicking the add button over and over again. As soon as he starts typing in a field and this field is no longer empty a new field should appear at the end of the list.
A delete button should also be available.

**Comment by M4R1KU** [comment]
fyi #310 duplicate
