### ISSUE TITLE
Jenkins server is unavailable

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#377]
If I try to access ci.pegnu.cloud I get a 502 - Bad Gateway error.
Therefore the ci status of our builds and pr's is not reported anymore.

@jmesserli could you plase take a look?

**Comment by jmesserli** [comment]
Should be back up soon

**Comment by needToRoll** [comment]
Awesome thx

**Comment by needToRoll** [comment]
[Safari - 06.03.2018, 07:57.pdf](https://github.com/outcobra/outstanding-cobra/files/1783825/Safari.-.06.03.2018.07.57.pdf)

Sadly I am still experiencing some kind of authentication issue...

**Comment by jmesserli** [comment]
That is a DNS issue, not an authentication issue; it's fixed now.
