### ISSUE TITLE
Agenda items for the 7. OC-Meetup

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#378]
To speed things up I would like to gather a list of (all) subjects we want to discuss tonight:

- [ ] Semester handling (in the context of the semester chooser)
- [ ] Discuss #379 `Security audit`
- [ ] Sprints - live or let die
- [ ] Release-planning 
- [ ] Discussions and enhancements walk-through

Feel free to edit or comment any other subject that comes to mind @outcobra/developers

**Comment by jmesserli** [comment]
This is over right.
