### ISSUE TITLE
Small error in README.md

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#4]
the gradle task is called bootRun and not runBoot

**Comment by jmesserli** [comment]
You are absolutely correct. You can fix it and create a pull request if you want @needToRoll

**Comment by needToRoll** [comment]
no i can't i only have read permissions @jmesserli

**Comment by jmesserli** [comment]
You have to push to a different branch than master. That's the point of pull requests.

**Comment by M4R1KU** [comment]
@jmesserli florian and vincent did only have read access to the repos. I created a new team and added everyone so that everyone has at least write access.
And personally I think that minor changes like a change in the README can be pushed directly to master.

**Comment by jmesserli** [comment]
@M4R1KU I agree that small changes should be directly pushable to master. On the other hand, we can't get too comfortable pushing stuff to master as we want to ensure a code review process.
But I am sure that we can keep this up by other means.

**Comment by M4R1KU** [comment]
@jmesserli as long as it is just a small change which includes about 4 lines max in just **one** file it's okay for me when it is pushed to master directly, otherwise I completely agree with the code review stuff which you've mentioned.

**Comment by jmesserli** [comment]
@m4r1ku great, I see it the same way. We might want to put that into the readme or something.

**Comment by needToRoll** [comment]
exactly @M4R1KU 
@jmesserli i think we are disciplined enough to do it right...

but at the moment the master branch is still protected and i can't push to it

**Comment by jmesserli** [comment]
I didn't doubt that @needtoroll. I will change the protectedness when I am not on mobile anymore. A typo won't ruin the project for now.

**Comment by jmesserli** [comment]
@needtoroll nevermind, I was able to remove the restriction. I would task you to add the information about code reviews to the readme :)

**Comment by needToRoll** [comment]
@jmesserli I have already made a pull request to resolve the issue

**Comment by jmesserli** [comment]
@needtoroll already reviewed it.
