### ISSUE TITLE
Fix Querydsl Support

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#41]
The way we have the project set up right now, we can't use Querydsl to do queries.

Options:
1. Make a second project that contains only entities and interfaces used by those entities @needToRoll 
2. Switch to JPA CriteriaApi and write a custom gradle plugin to handle the generation of the entities (cringe)
3. Fork kotlin gradle plugin to run it after `compileJava` task (ultra cringe)
4. Use JPA CriteriaApi without Metamodel generation which is not typesafe (quite cringe but easy to change now)

cc @outcobra/developers

**Comment by jmesserli** [comment]
Personally, I think we should try to go with 1.
If it works, it's the least effort that has to be done.

**Comment by needToRoll** [comment]
I think a separate project is the easiest way to go

**Comment by needToRoll** [comment]
@M4R1KU @Xanthos3 your opinion?

**Comment by M4R1KU** [comment]
@needToRoll I think least effort is best

**Comment by jmesserli** [comment]
So we'll create another project called `backend-model` which will generate Querydsl and while we're at it also JPA Metamodel classes (if we ever need them) using [this plugin](https://github.com/ewerk/gradle-plugins/tree/master/querydsl-plugin). `backend` will then depend on `backend-model` and since it's a different project, the generation will work just fine.
While we're at it, I suppose if we wanted we could now re-introduce lombok since it's a different project. Thoughts?

**Comment by needToRoll** [comment]
I agree on the idea of a second project. 
I came up with this idea because i had the same thought  back when we detected the lombok issue. I think the code woud be easier to maintain with lombok. But we struggled enought with framework-compatibility and it is the smaller effort to keep it the way it is now.

**Comment by jmesserli** [comment]
@needToRoll I agree that we should focus on getting Querydsl running first. After that though, I think it could be good to (in a future task) test Lombok and eventually rewrite the entities again for maintainability reasons.

**Comment by needToRoll** [comment]
@jmesserli agreed but i think we are under timepressure for the next 5 weeks so we may reconsider it after the GIBB-project
