### ISSUE TITLE
Icon on Management UI

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#45]
I'd like to discuss with you wether you like the current icons on the manage ui or not (and why).

![image](https://cloud.githubusercontent.com/assets/11866278/20315910/091ac32a-ab60-11e6-8834-0a7535350886.png)

You can request another icon for a specific thing on the UI, but keep the [material icons](peg.nu/micons) in mind.

**Comment by jmesserli** [comment]
On the second column, I'd use [date range](https://material.io/icons/#ic_date_range)
