### ISSUE TITLE
Upsource for Code Reviews

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#46]
Should I set up an [Upsource](https://www.jetbrains.com/upsource/) instance to do code reviews on in the future?

It has github integration and automatically syncs PRs and comments on them.

The biggest advantage over github is that it has:
* Static code analysis engine from IntellJ integrated
* Go to definition / find usages
* IntelliJ integration (plugin) -> reviewing directly in IntelliJ
* IntelliJ Double-Shift style search
* More analytics
* It's from Jetbrains

I've already had Upsource on my server before and it shouldn't be any pain to set it up.

**Comment by M4R1KU** [comment]
That sounds good to me. :smile:

**Comment by jmesserli** [comment]
You can read more about the github integration [here](https://blog.jetbrains.com/upsource/2016/04/12/github-integration-why-and-how/) if you are interested.

**Comment by M4R1KU** [comment]
Does it only support JavaScript or TypeScript too?

**Comment by jmesserli** [comment]
[This page](https://www.jetbrains.com/upsource/features/codeinsight.html#code-analysis) says:

```
Having IntelliJ IDEA in its core, Upsource boasts in-depth knowledge of Java,
JavaScript, PHP and Kotlin code. Specifically, it can execute server-side
static code analysis.
```

which could mean that Typescript will also be supported since IntelliJ supports Typescript. But they don't mention Typescript anywhere so I'm not sure.
The benefits would at least be available for Java/Kotlin though if Typescript is not supported.

**Comment by M4R1KU** [comment]
The benefits are clear and even if TypeScript is not completely supported we have enough other advantages in Java/Kotlin.

**Comment by jmesserli** [comment]
Upsource is now set up at https://upsource.pegnu.cloud.
Please login using Github on there @outcobra/developers .

All further code review should be done on there. It will be automatically synchronized with github. thanks!

**Comment by jmesserli** [comment]
If you set up your account please react with 👍 on this comment.
