### ISSUE TITLE
Using Spring Profiles

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#47]
[Spring Profiles](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html) should be used for things like disabling Auth0 in development or loading testdata.
Also, the h2 console :)

**Comment by M4R1KU** [comment]
Can we make a final list of all profiles with a short description for each one?

**Comment by jmesserli** [comment]
There will probably be more profiles to come but we can gather all profiles that we need at the moment.

**Comment by M4R1KU** [comment]
That would be great

**Comment by jmesserli** [comment]
I'll look at it in the evening.

**Comment by jmesserli** [comment]
Have a look at #103 when implementing this. The profiles we want to support are listed there.

**Comment by needToRoll** [comment]
Ok i have a question: do we really need to have a profile for both BASIC and AUTH0 I think this is just the one or the other...
Same situation with H2, POSTGRES and MySql

**Comment by jmesserli** [comment]
No we can go with one like "Security Mock". For the dbs we need all of them
because they are different serctions in the config file.

needToRoll <notifications@github.com> schrieb am Fr., 3. Feb. 2017, 22:34:

**Comment by needToRoll** [comment]
can't we use just 2 and the third as default?

**Comment by needToRoll** [comment]
I need help on more than one part off this task.
I hope to discuss this with another @outcobra/developers

**Comment by needToRoll** [comment]
There is no configuration and no profile for the postgreSQL database!
@jmesserli please complete this task before closing this issue.

**Comment by needToRoll** [comment]
@jmesserli status?

**Comment by M4R1KU** [comment]
I'd suggest close this issue and open a new one just for postgres. However currently we do not use postgres and probably this goes hanf in hand with the next deployment.
