### ISSUE TITLE
 Reformulate the testconcept and write it into the realisation-report

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#49]
According to the comments in the realisation-report document on google drive we have to explain why we are testing every part of the code the way we are testing it.

My idea is to explain that the api is the most important thing, and that we want to test it with unittests.
I am drafting my thoughts into the report right now. But you will have to review and rewrite it.

**Comment by jmesserli** [comment]
Can you add an estimate here? @needToRoll

**Comment by needToRoll** [comment]
Ï dont know yet, because i dont know how much i can get done today

**Comment by jmesserli** [comment]
Well it's an estimate for the whole thing, not a "how much is left". It doesn't have to be terribly accurate but it'd be good for tracking purposes to have one.

**Comment by needToRoll** [comment]
Ok we have delivered all the stuff
The rest falls under the documentation epic.
