### ISSUE TITLE
 Write unittests for the API endpoints

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#50]
We have to deliver test-code.

The enpoints (with all the services and stuff) are most likely the most important thing.
It shoud be possible to cover them with tests until tuesday.

I would recommand not to go too deep it only has to look good

**Comment by needToRoll** [comment]
You might want to split this task into smaller parts

**Comment by jmesserli** [comment]
7 services, 7 tests with ~5 methods, 1 Test about 30 mins ~~ 4 SP
