### ISSUE TITLE
Fix RequestFilter

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#67]
The request filter is currently failing because we are reading the request body from the request which is not intended. We might want to disable the filter temporarily and then think about a better way because i think fixing it like it is will bring trouble.

**Comment by jmesserli** [comment]
Status @needToRoll ?

**Comment by needToRoll** [comment]
I was not able to wrap the request properly so far. I think we should reconsider to do the authentication-check on the service level

**Comment by needToRoll** [comment]
@outcobra/developers with your permission I'd like to start implementing an authentication solution without the filter.
I must accept that I am unable to find an other way.

**Comment by jmesserli** [comment]
Okay with me. Try to do it as generic as possible.

needToRoll <notifications@github.com> schrieb am Sa., 11. Feb. 2017, 16:13:

**Comment by M4R1KU** [comment]
It is not fixed but there will be another solution.
