### ISSUE TITLE
Create Production SQL Create Script

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#68]
We need to provide a finished sql create schema and tables script because setting autoddl = create, compiling, deploying, undeploying, autoddl = verify, compiling, deploying for one deploy is not realistic.

For out-of-development usage, we might want to include something like [Flyway](https://flywaydb.org/) for migrations.

We might want to automate this using [a gradle plugin](https://divinespear.github.io/jpa-schema-gradle-plugin/).

**Comment by jmesserli** [comment]
The integration of the gradle plugin went not-particularly-good. I suggest that we move to Flyway now since we have to go that route at some point anyway. What do you guys think @outcobra/developers ?

**Comment by M4R1KU** [comment]
Flyway seems to be a good decision. This should really be made in Sprint 8.

**Comment by jmesserli** [comment]
Resources for implementing Flyway: 
* Spring Boot Docs: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-use-a-higher-level-database-migration-tool
* How Flyway works: https://flywaydb.org/getstarted/how
* Gradle First Steps: https://flywaydb.org/getstarted/firststeps/gradle

We may want to create a new issue for this though?

**Comment by jmesserli** [comment]
This is bigger than expected and can't be done with the time that we have left, moving to Sprint 9
