### ISSUE TITLE
Split DataLoader

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#70]
We should split our DataLoader in multiple DataLoaders which all handle only one Entity type.

Take a look at [this](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/Ordered.html) interface.

Implement it in the MIKOS-Style.

**Comment by jmesserli** [comment]
@M4R1KU what's the estimate on this one? I'd say about 2
