### ISSUE TITLE
Momentise all Dates

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#81]
To provide better time and data calculations we should change all existing dates to Moment objects.

This includes expecially the datepicker and the manage-ui currently.
We should also add a moment date pipe to provide formatting in the ui-code.

**Comment by jmesserli** [comment]
I think I'll be able to do this on Sunday

**Comment by M4R1KU** [comment]
Sunday? Which sunday? The one in 4 years? 🤔😂

**Comment by M4R1KU** [comment]
Because the @angular/material team has started working on a datepicker which is nearly finished and can be expected to release in one of the next 2-3 releases, we won't momentise all dates.
Most likely we will use the date type which the material datepicker will use (it only contains the date and not the time so there won't be such a timezone problem which we already had)
