### ISSUE TITLE
Merge Datepicker and Colorpicker SCSS

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#82]
Merge the scss parts of the datepicker and colorpicker which belong to the handling of the popup into something like a popup.scss.

Probably add a Popup super class which contains the basic handling like open, close etc.

**Comment by jmesserli** [comment]
Is this still needed since we will be using the datepicker from angular/material?

**Comment by M4R1KU** [comment]
No need anymore
