### ISSUE TITLE
Task not found

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#84]
When we request a task on the /task/:id endpoint which does not exist in the database the server throws exceptions.

![image](https://cloud.githubusercontent.com/assets/11866278/21567693/6250539e-ceae-11e6-84f2-ee7674c2f2ce.png)

**Comment by needToRoll** [comment]
whats the problem with that

**Comment by M4R1KU** [comment]
@needToRol do mean that question seriously?

**Comment by needToRoll** [comment]
Yes i think all the controllers behave like this

**Comment by jmesserli** [comment]
Well then it's not a task specific issue

needToRoll <notifications@github.com> schrieb am Sa., 31. Dez. 2016, 20:20:

**Comment by M4R1KU** [comment]
@needToRoll they act like this but this is clearly wrong and not what we want.

**Comment by needToRoll** [comment]
What would you want them to act like?

**Comment by M4R1KU** [comment]
Probably return a 404 or something that frontend can use....

**Comment by needToRoll** [comment]
this issue is resolved on the bugfix/controller branch

**Comment by M4R1KU** [comment]
Why are there also other changes on feature/create-task?

**Comment by jmesserli** [comment]
Please close the issue through a PR

**Comment by needToRoll** [comment]
because I made a small mistake while fixing the bug the ugly way

**Comment by M4R1KU** [comment]
I already merged it.

**Comment by jmesserli** [comment]
Neither `feature/task-ui` or `bugfix/controller` are merged to `develop`
