### ISSUE TITLE
Super-Service Backend

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#89]
We should create a "base-implementation" for a backend service which we can just extend if a specific service needs additional functionality. Our current services are mostly CRUD though.

**Comment by jmesserli** [comment]
_Note: we might be able to integrate #67 into this one (the super sevice could do checks)_

**Comment by M4R1KU** [comment]
@needToRoll did you make any progress on his issue?

**Comment by jmesserli** [comment]
@M4R1KU afaik nothing has been done on this one

**Comment by needToRoll** [comment]
pleas review @jmesserli @M4R1KU

**Comment by M4R1KU** [comment]
I'll review it in the evening.
Btw it would be very nice if you'd update the KDoc too. @needToRoll

**Comment by jmesserli** [comment]
who the fuck puts this many labels
