### ISSUE TITLE
Exchange PUT and POST on all create/update endpoints

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#98]
PUT and POST should be exchanged on create and update endpoints.
Create endpoints should be POST and update should be PUT.
This needs to be like this because PUT is idempotent however POST isn't.

**Comment by jmesserli** [comment]
I'd rather loose the create

**Comment by M4R1KU** [comment]
If we would only use PUT it wouldn't be correct REST design.

**Comment by needToRoll** [comment]
I agree with @M4R1KU... but i will reduce the services to one (save method)

**Comment by jmesserli** [comment]
Then we'll just use post

needToRoll <notifications@github.com> schrieb am Mi., 11. Jan. 2017, 14:21:

**Comment by M4R1KU** [comment]
@jmesserli naahh don't think so

**Comment by needToRoll** [comment]
i did some of it with the super service

**Comment by jmesserli** [comment]
Can you elaborate @needToRoll ? Is there still something that needs to be done or is this covered by #89 ?
